; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MinecraftServerInstaller"
#define MyAppVersion "4.0.1.0"
#define MyAppPublisher "SquidSpirit"
#define MyAppURL "https://squidspirit.ddns.net/tutorial/minecraft-server-installer/"
#define MyAppExeName "launcher.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DE07D4C8-9101-4839-A973-1B747192434B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=D:\Users\村﹙縪\Documents\Programming\Java\MinecraftServerInstaller\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=D:\Users\村﹙縪\Documents\Programming\Java\MinecraftServerInstaller
OutputBaseFilename=installer-setup
SetupIconFile=D:\Users\村﹙縪\Documents\Programming\Java\MinecraftServerInstaller\src\resources\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Users\村﹙縪\Documents\Programming\Java\MinecraftServerInstaller\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Users\村﹙縪\Documents\Programming\Java\MinecraftServerInstaller\MinecraftServerInstaller.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Users\村﹙縪\Documents\Programming\Java\MinecraftServerInstaller\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Users\村﹙縪\Documents\Programming\Java\MinecraftServerInstaller\lib\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

